# Generated by Django 5.0.6 on 2024-08-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_order_created_at_order_updated_at_report_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
    ]
