services:
  web:
    build: .
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles  # Debe coincidir con STATIC_ROOT en settings.py
      - media_volume:/code/media
    depends_on:
      - db

  db:
    image: mysql:8.0.39
    restart: always
    environment:
      MYSQL_DATABASE: almacen
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  static_volume:
  media_volume:
